"""Limits and tolerances shared by bandpass synthesis and response checks."""

import math

BANDPASS_EDGE_CALIBRATION_FBW_MAX = 0.10
BANDPASS_LUMPED_MODEL_CAUTION_FBW = 0.40

CALIBRATION_POINTS = 401
VALIDATION_POINTS = 2001
CALIBRATION_TOLERANCE = 2e-5
CALIBRATION_MAX_ITERATIONS = 12

EDGE_ERROR_LIMIT_REL = 1e-3
PASSBAND_SHAPE_ERROR_LIMIT_DB = 0.30
CHEBYSHEV_RIPPLE_ALLOWANCE_DB = 0.20
STOPBAND_SAMPLE_ERROR_LIMIT_DB = 8.0
THREE_DB_DOWN = 10.0 * math.log10(2.0)
